// <auto-generated />
using System;
using AcordIntake.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcordIntake.Api.Data.Migrations
{
    [DbContext(typeof(AcordDbContext))]
    partial class AcordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcordIntake.Api.Models.APSIncomingEntity", b =>
                {
                    b.Property<long>("APSIncomingEntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("APSIncomingEntityID"));

                    b.Property<string>("ACORDVendorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgencyCarrierCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CarrierCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyProducerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CopyInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorFacility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorFax")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorPhoneExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorStreet1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HIPPALocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<bool>("LoadToEISMain")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PatientDOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientGender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientMiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientPhone1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientPhone2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientSSN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientStreet1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PolicyAmcount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorAddess")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorPhoneExt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementAcctNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementInfoUniqueID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SendToCompany")
                        .HasColumnType("boolean");

                    b.Property<string>("TrackingID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransRefGUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentPhoneExt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingAgentZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("APSIncomingEntityID");

                    b.ToTable("aps_incoming", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
